/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package numeroazar;

/**
 *
 * @author ESFOT
 */

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }
Random numAleatorio = new Random();
        int x=numAleatorio.nextInt(1000);
        String mens=String.valueOf(x);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pJuego = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textIntento = new javax.swing.JTextField();
        btnIntento = new javax.swing.JButton();
        reinicio = new javax.swing.JButton();
        jblAviso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TENGO UN NUMERO ENTRE 1 Y 1000 PUEDES ADIVIRNARLO?????");

        textIntento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIntentoActionPerformed(evt);
            }
        });

        btnIntento.setText("INTENTAR");
        btnIntento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntentoActionPerformed(evt);
            }
        });

        reinicio.setText("REINICIO");
        reinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinicioActionPerformed(evt);
            }
        });

        jblAviso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout pJuegoLayout = new javax.swing.GroupLayout(pJuego);
        pJuego.setLayout(pJuegoLayout);
        pJuegoLayout.setHorizontalGroup(
            pJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pJuegoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pJuegoLayout.createSequentialGroup()
                        .addComponent(textIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIntento)
                        .addGap(26, 26, 26)
                        .addComponent(reinicio)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pJuegoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pJuegoLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pJuegoLayout.setVerticalGroup(
            pJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIntento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntento)
                    .addComponent(reinicio))
                .addGap(18, 18, 18)
                .addComponent(jblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textIntentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIntentoActionPerformed
 
         
    }//GEN-LAST:event_textIntentoActionPerformed

    private void btnIntentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntentoActionPerformed
        // TODO add your handling code here:
       String prueba=textIntento.getText();
       int y=Integer.parseInt(prueba);
        if(y==x){
        pJuego.setBackground(Color.GREEN); 
        JOptionPane.showMessageDialog(rootPane, "CORRECTO");
            textIntento.enable(false);
            jblAviso.setText("");
        }else if(y<x){
        int a=x-y;
        if(a>=100){
        pJuego.setBackground(Color.BLUE); 
        jblAviso.setText("DEMASIADO BAJO!");
        
        }else if(a<100){
            pJuego.setBackground(Color.RED); 
        jblAviso.setText("DEMASIADO BAJO!");
        
        }
        }else if(y>x){
        int a=y-x;
        if(a>=100){
        pJuego.setBackground(Color.BLUE); 
        jblAviso.setText("DEMASIADO ALTO!");
        }else if(a<100){
            pJuego.setBackground(Color.RED); 
        jblAviso.setText("DEMASIADO ALTO!");
        
        }
        
        }
    }//GEN-LAST:event_btnIntentoActionPerformed

    private void reinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinicioActionPerformed
        
        int z=numAleatorio.nextInt(1000);
        x=z;
        mens=String.valueOf(x);
        textIntento.setText("");
         textIntento.enable(true);
        
    }//GEN-LAST:event_reinicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        
      
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jblAviso;
    private javax.swing.JPanel pJuego;
    private javax.swing.JButton reinicio;
    private javax.swing.JTextField textIntento;
    // End of variables declaration//GEN-END:variables
}
